# Generated by Django 3.0.7 on 2020-06-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('provider', models.CharField(choices=[('virtualbox', 'virtualbox')], max_length=50)),
                ('address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('cores', models.PositiveSmallIntegerField()),
                ('memory', models.PositiveSmallIntegerField()),
                ('status', models.CharField(blank=True, choices=[('Off', 'Off'), ('Running', 'Running'), ('Rebooting', 'Rebooting'), ('Deleted', 'Deleted'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('last_report_date', models.DateTimeField(null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed'), ('Unknown', 'Unknown')], default='Pending', max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Environment', unique=True)),
            ],
        ),
    ]
