# Generated by Django 3.0.7 on 2020-06-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentdeployment',
            name='environment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='environment.Environment'),
        ),
    ]
