# Generated by Django 3.0.7 on 2020-06-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20200628_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvironmentDeployment',
            new_name='Deployment',
        ),
    ]
