# Generated by Django 3.0.7 on 2020-06-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_auto_20200629_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('start', 'start'), ('stop', 'stop'), ('reset', 'reset'), ('delete', 'delete')], max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Dispatched', 'Dispatched'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed'), ('Unknown', 'Unknown')], default='Scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='environment',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
