# Generated by Django 3.0.7 on 2020-06-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0006_auto_20200629_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Environment'),
        ),
    ]
