# Generated by Django 3.0.7 on 2020-06-28 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20200628_0229'),
        ('deployment', '0002_auto_20200628_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionenvironment',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Scheduled'), ('2', 'Running'), ('3', 'Success'), ('4', 'Failed'), ('5', 'Unknown')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='executionenvironment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.WorkerNode'),
        ),
    ]
