# Generated by Django 3.0.7 on 2020-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_auto_20200628_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionenvironment',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionenvironment',
            name='provider',
            field=models.CharField(choices=[('virtualbox', 'virtualbox')], max_length=50),
        ),
        migrations.AlterField(
            model_name='executionenvironment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed'), ('Unknown', 'Unknown')], default='Pending', max_length=50),
        ),
    ]
