# Generated by Django 3.0.7 on 2020-06-28 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_auto_20200628_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionenvironment',
            old_name='details',
            new_name='detail',
        ),
    ]
