# Generated by Django 3.0.7 on 2020-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0005_auto_20200628_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionenvironment',
            name='cpus',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='executionenvironment',
            name='memory',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
