# Generated by Django 3.0.7 on 2020-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('cpus', models.PositiveSmallIntegerField()),
                ('cpus_reserved', models.PositiveSmallIntegerField(default=0)),
                ('memory', models.PositiveSmallIntegerField()),
                ('memory_reserved', models.PositiveSmallIntegerField(default=0)),
                ('last_health_report_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
