# Generated by Django 3.0.7 on 2020-06-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workernode',
            name='last_health_report_date',
            field=models.DateTimeField(null=True),
        ),
    ]
