# Generated by Django 3.0.7 on 2020-06-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_workernode_last_health_report_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workernode',
            old_name='ip_address',
            new_name='address',
        ),
    ]
