# Generated by Django 3.0.7 on 2020-06-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20200628_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workernode',
            name='address',
            field=models.GenericIPAddressField(),
        ),
    ]
