# Generated by Django 3.0.7 on 2020-06-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20200628_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workernode',
            name='address',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
