# Generated by Django 3.0.7 on 2020-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20200628_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workernode',
            name='cpus',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workernode',
            name='cpus_reserved',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workernode',
            name='memory',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workernode',
            name='memory_reserved',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
